<?php

namespace App\Enums;

enum WorkflowWindowCode: string
{
    case REGISTRATION = 'REGISTRATION';
    case ABSTRACT_SUBMISSION = 'ABSTRACT_SUBMISSION';
    case ACCEPTED_AUTHOR_PAYMENT = 'ACCEPTED_AUTHOR_PAYMENT';
    case FULL_ARTICLE = 'FULL_ARTICLE';
    case PRESENTER_CONFIRMATION = 'PRESENTER_CONFIRMATION';
    case REVISION = 'REVISION';
}
